platform :ios, ‘9.0’
target 'BJHybrid' do
    
    pod 'WebViewJavascriptBridge'
#    pod 'WKWebViewJavascriptBridge', '~> 1.2.0'
    pod 'WKWebViewJavascriptBridge'

    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            if target.name == '<insert target name of your pod here>'
                target.build_configurations.each do |config|
                    config.build_settings['SWIFT_VERSION'] = '3.0'
                end
            end
        end
    end
    
end
