platform :ios, '10.0'
target 'BJHybrid' do
        
    pod 'WebViewJavascriptBridge', '~> 6.0.2'
    pod 'WKWebViewJavascriptBridge', '~> 1.2.1'

    
#    post_install do |installer|
#        installer.pods_project.targets.each do |target|
#            if target.name == '<insert target name of your pod here>'
#                target.build_configurations.each do |config|
#                    config.build_settings['SWIFT_VERSION'] = '3.0'
#                end
#            end
#        end
#    end
#
end
